### PR TITLE
fix #21 - create dependencies field if missing

### LINKED ISSUE #21: Empty dependencies field in package.json breaks build process
So... I've been struggling to get an existing project into an nx monorepo and now I know why.

It's fairly natural to copy over all the existing code into a newly generated project, and cut and paste all of the function app's dependencies to the root `package.json`.

But if you don't leave an empty `dependencies` field in the function app project's `package.json`, the generator will fail to copy over the relevant dependencies during build. What's worse is there's no relevant error message either.

#### Steps to reproduce:

In an nx function app project created with `@nxazure/func`, delete the `dependencies` section completely. Try a build. It'll fail with the error message `Cannot read properties of undefined (reading 'tsconfig-paths')`, which isn't exactly helpful.

If you just include `"dependencies": {},` then it'll work just fine, building and running smoothly.

I hope this bug report helps, @AlexPshul. Thanks again for all your hard work on this generator.

### PR DESCRIPTION
**Pull request by JonSilver**

### CODE REVIEW

File: packages/func/src/executors/common/get-copy-package-to-app-transformer-factory.ts [hunk 1]
```diff
@@ -32,7 +32,11 @@ export const getCopyPackageToAppTransformerFactory = (context: ExecutorContext)
       if (isImportDeclaration(node)) {
         const cleanedModuleName = node.moduleSpecifier.getText().replace(/['"]/g, '');
         const moduleInOriginalPackageJson = findModule(originalPackageJson.dependencies, cleanedModuleName);
-        // If the original package.json has the dependency, copy it to the app package.json
+         // Create a dependencies section in the app package.json if it doesn't exist
+        if (!appPackageJson.dependencies) 
+          appPackageJson.dependencies = {};
```
Comment (AlexPshul) [inline packages/func/src/executors/common/get-copy-package-to-app-transformer-factory.ts:37]: The `visitChild` will be called on each node in each file of the program.
I think it would be better to have the if statement happen outside of the `visitChild`, so it would run only once.

**Review by AlexPshul — APPROVED** [review]
Thanks for the PR, @JonSilver!
I really appreciate the time you took to solve this and submit it. 🙏 

I had only 1 minor comment

File: packages/func/src/executors/common/get-copy-package-to-app-transformer-factory.ts (hunk 1 above)
Comment (JonSilver) [reply packages/func/src/executors/common/get-copy-package-to-app-transformer-factory.ts:37]: I see what you mean, but for this fix I considered it an unnecessary optimisation because even if a falsey nullish check were executed for thousands of nodes it wouldn't have any discernible affect on performance.
